#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d α β γ δ ε ζ qī η θ ι

bspc config border_width         8
bspc config window_gap          30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Border colors
bspc config normal_border_color "#478061"
bspc config focused_border_color "#478061"
bspc config urgent_border_color "#478061"
bspc config presel_border_color "#478061"
